version: "3"

volumes:
  esdata:

services:
  node-exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node_exporter
    links:
      - fluentd
    depends_on:
      - fluentd
    restart: always
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|var/lib/docker/containers|var/lib/docker/overlay2|run/docker/netns|var/lib/docker/aufs)($$|/)"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "0.0.0.0:24224"
        fluentd-retry-wait: 3s


  fluent-bit:
    image: fluent/fluent-bit:1.4.3
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/config/fluent-bit.conf  
    restart: always
    ports:
      - "43000:43000"
      - "43000:43000/udp"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/config/fluent-bit.conf
    links:
      - fluentd
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "0.0.0.0:24224"
        fluentd-retry-wait: 3s
        
  fluentd: 
    build: ./fluentd
    restart: unless-stopped
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 24224:24224
      - 24224:24224/udp

  elasticsearch:
    image: elasticsearch:7.17.0
    expose:
      - 9200
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    

  kibana:
    image: kibana:7.17.0
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
